before:
  hooks:
  - go generate ./...

builds:
- env:
  - CGO_ENABLED=0

  goos:
  - linux

  goarch:
  - arm64
  - arm

  goarm:
  - 6
  - 7

archive:
  replacements:
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

sign:
  artifacts: checksum

snapshot:
  name_template: "{{ .Tag }}-next"

nfpm:
  replacements:
    386: i386
    amd64: x86_64
  vendor: AppsCode Inc.
  homepage: https://appscode.com
  description: hello-grpc
  license: Apache 2.0

  formats:
  - deb
  - rpm

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  draft: true

dockers:
- image: tahsin/hello-grpc-arm64
  dockerfile: hack/docker/Dockerfile
  goos: linux
  goarch: arm64
  binary: hello-grpc
- image: tahsin/hello-grpc-arm7
  dockerfile: hack/docker/Dockerfile
  goos: linux
  goarch: arm
  goarm: 7
  binary: hello-grpc
- image: tahsin/hello-grpc-arm6
  dockerfile: hack/docker/Dockerfile
  goos: linux
  goarch: arm
  goarm: 6
  binary: hello-grpc
