# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
#

before:
  hooks:
  - go generate ./...
    #   - env ARCH=amd64 BASE=alpine ./hack/docker/generate.sh
    #   - env ARCH=arm64 BASE=alpine ./hack/docker/generate.sh
    #   - env ARCH=arm6 BASE=armhf/alpine ./hack/docker/generate.sh
    #   - env ARCH=arm7 BASE=armhf/alpine ./hack/docker/generate.sh

builds:
- env:
  - CGO_ENABLED=0

  goos:
  - linux
  - darwin
  - windows

  goarch:
  - amd64
  - arm
  - arm64

  goarm:
  - 6
  - 7

archive:
  replacements:
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

sign:
  artifacts: checksum

snapshot:
  name_template: "{{ .Tag }}-next"

nfpm:
  replacements:
    386: i386
    amd64: x86_64
  vendor: AppsCode Inc.
  homepage: https://appscode.com
  description: hello-grpc
  license: Apache 2.0

  formats:
  - deb
  - rpm

brew:
  github:
    owner: appscode
    name: homebrew-tap
  homepage: https://appscode.com
  description: hello-grpc

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

dockers:
- image: tahsin/hello-grpc-amd64
  dockerfile: hack/docker/Dockerfile
  goos: linux
  goarch: amd64
  binary: hello-grpc
- image: tahsin/hello-grpc-arm64
  dockerfile: hack/docker/Dockerfile
  goos: linux
  goarch: arm64
  binary: hello-grpc
- image: tahsin/hello-grpc-arm7
  dockerfile: hack/docker/Dockerfile
  goos: linux
  goarch: arm
  goarm: 7
  binary: hello-grpc
- image: tahsin/hello-grpc-arm6
  dockerfile: hack/docker/Dockerfile
  goos: linux
  goarch: arm
  goarm: 6
  binary: hello-grpc
